"""
Comprehensive Live Fleet Diagnostic & Integration Test for Mnemosyne v3.4.0.
Exercises all 8 MCP tools and cross-agent memory sharing across all 5 production containers.
"""

import os
import sys
import json
import time
from datetime import datetime, timezone
from pathlib import Path

# Verify Mnemosyne import and version
try:
    import mnemosyne
    from mnemosyne import UnifiedMemorySystem, __version__
    from mnemosyne.mcp_server import MCPServer
    from mnemosyne.core import SecurityCheckError
except ImportError as e:
    print(f"FATAL: Unable to import mnemosyne: {e}")
    sys.exit(1)

print(f"=== Mnemosyne Core Version: {__version__} ===")

AGENT_NAME = os.environ.get("MEMORY_AGENT_NAME", "unknown-agent")
VAULT_PATH = os.environ.get("MEMORY_VAULT_PATH", "/opt/data/vault")
DB_DSN = os.environ.get("MEMORY_DB_DSN")
SHARED_DSN = os.environ.get("MEMORY_SHARED_DSN")

print(f"Agent: {AGENT_NAME}")
print(f"Vault: {VAULT_PATH}")
print(f"Private DB: {DB_DSN}")
print(f"Shared DB: {SHARED_DSN}")

# 1. Initialize UnifiedMemorySystem
try:
    mem = UnifiedMemorySystem(
        vault_path=VAULT_PATH,
        dsn=DB_DSN,
        shared_dsn=SHARED_DSN,
        agent_name=AGENT_NAME
    )
    print("✅ UnifiedMemorySystem initialized successfully")
except Exception as e:
    print(f"❌ UnifiedMemorySystem initialization failed: {e}")
    sys.exit(1)

# 2. Test MCP Server instantiation & Tools list
try:
    server = MCPServer(memory=mem)
    tools = server._get_tools()
    tool_names = [t["name"] for t in tools]
    assert len(tools) == 8, f"Expected 8 tools, got {len(tools)}"
    print(f"✅ MCPServer registered 8 tools: {', '.join(tool_names)}")
except Exception as e:
    print(f"❌ MCPServer initialization/tools verification failed: {e}")
    sys.exit(1)

# 3. Test Tool 1: memory_remember
test_title = f"Diagnostic Test Note - {AGENT_NAME}"
test_content = (
    f"This is an automated diagnostic test note generated by {AGENT_NAME}.\n"
    f"It validates HNSW pgvector indexing, atomic Markdown vault serialization, and RRF retrieval.\n"
    f"Reference link: [[Global Architecture Blueprint]]"
)

try:
    rem_res = mem.remember(
        title=test_title,
        content=test_content,
        tags=["diagnostic", "automated-test", AGENT_NAME],
        note_type="diagnostic",
        salience=0.9,
        wing="diagnostics",
        room="e2e-testing",
        pinned=True
    )
    assert rem_res.get("success") is True, f"remember returned false: {rem_res}"
    print(f"✅ Tool 1 (memory_remember): created note '{test_title}' (id={rem_res.get('note_id')})")
except Exception as e:
    print(f"❌ Tool 1 (memory_remember) failed: {e}")
    sys.exit(1)

# 4. Verify physical Markdown file on disk
try:
    vault_file = Path(VAULT_PATH) / "diagnostics" / "e2e-testing" / f"{test_title}.md"
    # Fallback to direct root if subfolder hierarchy varies
    if not vault_file.exists():
        found = list(Path(VAULT_PATH).rglob(f"*{test_title}*.md"))
        assert len(found) > 0, f"Markdown file not found in vault: {VAULT_PATH}"
        vault_file = found[0]
    
    file_text = vault_file.read_text(encoding="utf-8")
    assert "diagnostic" in file_text
    print(f"✅ Vault File Verified on Disk: {vault_file} ({len(file_text)} bytes)")
except Exception as e:
    print(f"❌ Vault verification failed: {e}")
    sys.exit(1)

# 5. Test Tool 3: memory_recall (Hybrid, Semantic, Keyword, Graph)
try:
    # Hybrid Search
    hybrid_res = mem.recall(
        query="diagnostic automated test HNSW",
        mode="hybrid",
        top_k=3,
        scope={"wing": "diagnostics"}
    )
    assert len(hybrid_res) > 0, "Hybrid recall returned 0 results"
    assert hybrid_res[0]["title"] == test_title
    assert "<recalled_memory_context" in hybrid_res[0]["formatted_context"]
    print(f"✅ Tool 3 (memory_recall - Hybrid): successfully retrieved top match with XML context")

    # Keyword Search
    kw_res = mem.recall(query=AGENT_NAME, mode="keyword", top_k=3)
    assert len(kw_res) > 0, "Keyword recall returned 0 results"
    print(f"✅ Tool 3 (memory_recall - Keyword): successfully retrieved {len(kw_res)} match(es)")

    # Semantic Search
    sem_res = mem.recall(query="automated validation of vector embeddings", mode="semantic", top_k=3)
    assert len(sem_res) > 0, "Semantic recall returned 0 results"
    print(f"✅ Tool 3 (memory_recall - Semantic): successfully retrieved {len(sem_res)} match(es)")
except Exception as e:
    print(f"❌ Tool 3 (memory_recall) failed: {e}")
    sys.exit(1)

# 6. Test Tool 4: memory_ingest_session
try:
    sample_transcript = (
        f"User: Agent {AGENT_NAME}, please run the memory validation checklist.\n"
        f"Assistant: Running comprehensive checks on HNSW index, connection pool, and vault storage.\n"
        f"User: Verify turn boundary chunking."
    )
    ingest_res = mem.ingest_session(
        transcript=sample_transcript,
        wing="diagnostics",
        room="transcripts"
    )
    assert ingest_res.get("success") is True
    print(f"✅ Tool 4 (memory_ingest_session): ingested {ingest_res.get('units_ingested')} units from {ingest_res.get('turns_total')} turns")
except Exception as e:
    print(f"❌ Tool 4 (memory_ingest_session) failed: {e}")
    sys.exit(1)

# 7. Test Tool 5: memory_timeline
try:
    tl_res = mem.timeline(limit=5)
    assert len(tl_res) > 0, "Timeline returned 0 records"
    actions = [r.get("action", r.get("operation", "unknown")) for r in tl_res]
    print(f"✅ Tool 5 (memory_timeline): retrieved {len(tl_res)} recent actions ({', '.join(actions[:3])})")
except Exception as e:
    print(f"❌ Tool 5 (memory_timeline) failed: {e}")
    sys.exit(1)

# 8. Test Tool 6: memory_history
try:
    # Update note to generate version history
    mem.remember(
        title=test_title,
        content=test_content + "\n\nUpdated edit to test note_versions table.",
        tags=["diagnostic", "updated"],
        wing="diagnostics",
        room="e2e-testing"
    )
    hist_res = mem.note_history(title=test_title, limit=5)
    print(f"✅ Tool 6 (memory_history): note history contains {len(hist_res)} version snapshot(s)")
except Exception as e:
    print(f"❌ Tool 6 (memory_history) failed: {e}")
    sys.exit(1)

# 9. Test Tool 7: memory_remind_me
try:
    remind_res = mem.remind_me(
        title="Check Fleet Health",
        content="Automated reminder for memory maintenance.",
        trigger_at="2026-09-01T12:00:00Z",
        recurring="weekly"
    )
    assert remind_res.get("success") is True
    print(f"✅ Tool 7 (memory_remind_me): scheduled prospective reminder for {remind_res.get('trigger_at')}")
except Exception as e:
    print(f"❌ Tool 7 (memory_remind_me) failed: {e}")
    sys.exit(1)

# 10. Test Tool 8: memory_audit
try:
    stats = mem.stats()
    health = server._health()
    assert health["server"]["status"] == "healthy"
    assert health["server"]["version"] == "3.4.0"
    assert health["store"]["shared_store"] is True
    print(f"✅ Tool 8 (memory_audit): Health status={health['server']['status']}, Version={health['server']['version']}, DB Notes={stats.get('total_notes', stats.get('notes', 'N/A'))}")
except Exception as e:
    print(f"❌ Tool 8 (memory_audit) failed: {e}")
    sys.exit(1)

# 11. Test Tool 2 & Security: memory_publish_shared & credential guard
try:
    # A. Sensitive key rejection test
    bad_payload = "Publishing secret key sk-ant-api03-abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890 to shared"
    sec_res = mem.publish_shared(
        title="Leaked Key Attempt",
        content=bad_payload
    )
    assert sec_res.get("success") is False, "Security screening failed to block Anthropic key!"
    print("✅ Tool 2 Security Gate: successfully blocked private API key from shared_db")

    # B. Legitimate shared note publication
    shared_title = f"Fleet Diagnostic Policy from {AGENT_NAME}"
    shared_content = f"Global fleet policy published by {AGENT_NAME} at {datetime.now(timezone.utc).isoformat()}."
    pub_res = mem.publish_shared(
        title=shared_title,
        content=shared_content,
        tags=["fleet", "policy", "diagnostic"],
        wing="shared",
        room="general"
    )
    assert pub_res.get("success") is True, f"publish_shared returned error: {pub_res}"
    print(f"✅ Tool 2 (memory_publish_shared): published shared policy '{shared_title}'")
except Exception as e:
    print(f"❌ Tool 2 (memory_publish_shared) failed: {e}")
    sys.exit(1)

print(f"\n🎉 ALL 8 MCP TOOLS & SECURITY GATES PASSED FOR AGENT: {AGENT_NAME}\n")
